service: import-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    bucketName: "arn:aws:s3:::my-2nd-app-er-files"
    SQS_URL:
      Ref: SQSQueue

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::my-2nd-app-er-files"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::my-2nd-app-er-files/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt: [ SQSQueue, Arn ]

functions:
  import:
    handler: handler.importProductsFile
    events:
      - http:
          path: product/import
          method: get
          authorizer:
            name: hznh2o
            arn: "arn:aws:lambda:us-east-1:602015266074:function:authorization-service-dev-authorizer"
            resultTtlInSeconds: 0
            identifySource: method.requset.header.Authorization
            type: token
  parse:
    handler: handler.parseProductsFile
    events:
      - s3:
          bucket: "my-2nd-app-er-files"
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

resources:
  Outputs:
    SQSQueueUrl:
      Value:
        Ref: SQSQueue
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    # SNSTopic:
    #   Type: AWS::SNS::TOPIC
    #   Properties:
    #     TopicName: createProductTopic
    # SNSSubscription:
    #   Type: AWS::SNS::Subscription
    #   Properties:
    #     Endpoint: sortayne@gmail.com
    #     Protocol: email
    #     TopicArn:
    #       Ref: SNSTopic
